# Generated by Django 4.2 on 2023-04-10 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Show', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Auto',
            new_name='Auto_Camera',
        ),
        migrations.RenameField(
            model_name='auto_camera',
            old_name='Couter',
            new_name='Couters',
        ),
        migrations.RenameField(
            model_name='auto_camera',
            old_name='Timer',
            new_name='Timers',
        ),
    ]
