# Generated by Django 3.2.7 on 2022-12-17 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_subject_host'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
