# Generated by Django 3.2.7 on 2022-12-20 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20221220_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='files'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='url',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='video',
            field=models.FileField(blank=True, default=None, null=True, upload_to='videos'),
        ),
    ]
