# Generated by Django 3.2.7 on 2022-12-22 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_user_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='access',
            field=models.CharField(choices=[('SV', 'Student'), ('GV', 'Teacher'), ('AD', 'Admin')], default='SV', max_length=2),
        ),
    ]
