# Generated by Django 3.2.7 on 2022-12-22 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_user_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='access',
            field=models.IntegerField(choices=[('Cơ bản', 'Cơ bản'), ('Cơ sở', 'Cơ sở'), ('Chuyên ngành', 'Chuyên ngành')]),
        ),
    ]
