# Generated by Django 3.2.7 on 2022-12-22 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_subject_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='fkmajor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.major'),
        ),
    ]
