# Generated by Django 3.2.7 on 2023-01-26 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_alter_user_access'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='file',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='url',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='video',
        ),
        migrations.CreateModel(
            name='video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, default=None, null=True, upload_to='videos')),
                ('fkchapter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.chapter')),
            ],
        ),
        migrations.CreateModel(
            name='file',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, default=None, null=True, upload_to='files')),
                ('fkchapter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.chapter')),
            ],
        ),
    ]
