# Generated by Django 3.2.7 on 2023-01-26 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_auto_20230126_2054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='fkchapter',
        ),
        migrations.AddField(
            model_name='chapter',
            name='file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='files'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='url',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='chapter',
            name='video',
            field=models.FileField(blank=True, default=None, null=True, upload_to='videos'),
        ),
        migrations.DeleteModel(
            name='file',
        ),
        migrations.DeleteModel(
            name='video',
        ),
    ]
