# Generated by Django 3.2.7 on 2023-02-01 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_auto_20230126_2104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='file',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='url',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='video',
        ),
        migrations.CreateModel(
            name='video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, default=None, null=True, upload_to='videos')),
                ('url', models.CharField(max_length=200)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('fkchapter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.chapter')),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
        migrations.CreateModel(
            name='file',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, default=None, null=True, upload_to='files')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('fkchapter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.chapter')),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
    ]
