# Generated by Django 3.2.7 on 2023-02-07 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_alter_subject_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='access',
            field=models.CharField(choices=[('CB', 'Cơ bản'), (1, 'CS'), (2, 'CN')], default='Cơ bản', max_length=50),
        ),
    ]
