# Generated by Django 3.2.7 on 2023-02-07 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_alter_subject_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='access',
            field=models.CharField(choices=[('Cơ bản', 'Cơ bản'), ('Cơ sở', 'Cơ sở'), ('Chuyên ngành', 'Chuyên ngành')], default='Cơ bản', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='access',
            field=models.CharField(choices=[('0', 'SV'), ('1', 'GV'), ('2', 'AD')], default='0', max_length=2),
        ),
    ]
