# Generated by Django 3.2.7 on 2023-02-07 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_auto_20230207_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='access',
            field=models.CharField(choices=[(0, 'Cơ bản'), (1, 'Cơ sở'), (2, 'Chuyên ngành')], default=0, max_length=50),
        ),
    ]
