# Generated by Django 3.2.7 on 2023-02-07 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_alter_subject_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='access',
            field=models.CharField(choices=[('0', 'Cơ bản'), ('1', 'Cơ sở'), ('2', 'Chuyên ngành')], default='0', max_length=2),
        ),
    ]
